name: java_fullstack_mysql_containers

services:
    
    java_fullstack_mysql:
        image: mysql:8.3
        container_name: java_fullstack_mysql_container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            #MYSQL_DATABASE: "employeeservice_db"               databases will be created by the init.sql script
        networks: 
            - java_fullstack_network
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - java_fullstack_mysql_volume:/var/lib/mysql
        
    phpmyadmin_java_fullstack:
        image: phpmyadmin
        container_name: java_fullstack_phpmyadmin_container
        ports:
            - "8085:80"
        environment:
            PMA_HOST: java_fullstack_mysql_container
        networks:
            - java_fullstack_network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"

networks:
    java_fullstack_network:

volumes:
    java_fullstack_mysql_volume:
        name: "java_fullstack_mysql_volume"