server:
  port: 8090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #ProductCatalog route
        - id: productcatalog-service
          uri: lb://productcatalog-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}

        #Shoppingcart route
        - id: shoppingcart-service
          uri: lb://shoppingcart-service
          predicates:
            - Path=/shoppingcart/**
          filters:
            - RewritePath=/shoppingcart/(?<path>.*), /$\{path}

        #Whishlist route
        - id: whishlist-service
          uri: lb://whishlist-service
          predicates:
            - Path=/whishlist/**
          filters:
            - RewritePath=/whishlist/(?<path>.*), /$\{path}

        #logbook Route
        - id: logbook-service
          uri: lb://logbook-service
          predicates:
            - Path=/logbook/**
          filters:
            - RewritePath=/logbook/(?<path>.*), /$\{path}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
